install.packages("ISLR")
library(ISLR)
x = matrix(data = c(1,2,3,4), nrow = 2, ncol = 2)
x
sqrt(x)
x^2
x= rnorm(50)
y = x + rnorm(50, mean = 50, sd = 1)
cor(x,y)
set.seed(1303)
rnorm(50)
set.seed(3)
y = rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
x = rnorm(100)
y = rnorm(100)
plot(x, y)
plot(x, y, xlab = "This is the x-axis", ylab = "This is the y-axis", main = "Plot of X vs Y")
pdf("Figure.pdf")
plot(x, y, col = "green")
dev.off()
x = seq(1, 10)
x
x = 1:10
x
x = seq(-pi, pi, length = 50)
x
y = x
f = outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x, y, f)
contour(x, y, f, nlevels = 45, add = T)
fa = (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
image(x, y, fa)
persp(x, y, fa)
persp(x,y, fa, theta = 30)
persp(x, y, fa, theta = 30, phi = 40)
A = matrix(1:16, 4, 4)
A
A[2,3]
A[1:3, 2:4]
A[-c(1,3),]
dim(A)
Auto = read.csv("Auto.csv")
dim(Auto)
names(Auto)
plot(Auto$cylinders, Auto$mpg)
attach(Auto)
cylinders = as.factor(cylinders)
plot(cylinders, mpg)
plot(cylinders, mpg, col = "red", varwidth = T)
plot(cylinders, mpg, col = "red", varwidth = T, horizontal = T)
plot(cylinders, mpg, col = "red", varwidth = T, xlab = "Cylinders", ylab = "mpg")
hist(mpg)
hist(mpg, col = 2)
hist(mpg, col = 2, breaks = 15)
pairs(Auto)
pairs(~ mpg + displacement + horsepower + weight + acceleration, Auto)
plot(horsepower, mpg)
identify(horsepower, mpg, name)
summary(Auto)
summary(mpg)
